epoch: 100
train_patience: 5
batch_size: 32
valid_ratio: 0.1
test_ratio: 0.15
fc: Linear
loss: focal_loss
lr: 0.0001
weight_decay: 0.00005
seed: 420
device: cpu
#mtcnn
image_size: 224
margin: 0
min_face_size: 20
threshold: [0.6, 0.7, 0.7]
factor: 0.709
prewhiten: True
pretrained: True
kernel: rbf
classifier: svm
eval: normal